'use strict';
let researchBusy=false;
const researchPreviousView=view;
view=function(name){$('research-view').classList.toggle('hidden',name!=='research');$('nav-research').classList.toggle('active',name==='research');if(name==='research'){for(const item of ['home','library','search','review','drafting']){$(item+'-view').classList.add('hidden');$('nav-'+item)?.classList.remove('active');}$('breadcrumb').textContent='Legal Research';safe(loadResearchScreen)();return;}researchPreviousView(name);};
$('nav-research').onclick=()=>view('research');
async function loadResearchScreen(){const history=await api('/api/v1/research');$('research-history').replaceChildren();for(const memo of history.items){const b=node('button','button subtle',memo.question+' · '+memo.status);b.onclick=safe(()=>showResearch(memo.id));$('research-history').append(b);}const all=[];let cursor=null;do{const page=await api('/api/v1/documents?status=ready&limit=100'+(cursor?'&cursor='+encodeURIComponent(cursor):''));all.push(...page.items.filter(d=>d.metadata.document_type!=='user_input'));cursor=page.next_cursor;}while(cursor);$('research-sources').replaceChildren();for(const doc of all){const label=node('label','source-choice'),box=node('input');box.type='checkbox';box.value=doc.id;label.append(box,document.createTextNode(doc.name));$('research-sources').append(label);}}
async function waitResearch(id){for(let n=0;n<1800;n++){const job=await api('/api/v1/jobs/'+id);$('research-progress').textContent=job.status+' · '+Math.round(job.progress*100)+'%';if(terminal.has(job.status))return job;await new Promise(resolve=>setTimeout(resolve,1500));}throw new Error('Task still running. Reopen it from history.');}
async function followResearch(ticket){$('research-cancel').classList.remove('hidden');$('research-cancel').onclick=safe(()=>api('/api/v1/jobs/'+ticket.job_id+'/cancel',{method:'POST',json:{}}));try{await waitResearch(ticket.job_id);await showResearch(ticket.research_id);}finally{$('research-cancel').classList.add('hidden');}}
$('research-form').onsubmit=safe(async e=>{e.preventDefault();if(researchBusy)return;researchBusy=true;$('research-run').disabled=true;try{const scope=$('research-scope').value.trim(),code=/^IN(?:-[A-Z]{2})?$/.test(scope);const aliases={'Supreme Court':'Supreme Court of India','Delhi High Court':'High Court of Delhi','Bombay High Court':'High Court of Bombay'};const ticket=await api('/api/v1/research',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},json:{question:$('research-question').value,context_document_ids:[...$('research-sources').querySelectorAll('input:checked')].map(i=>i.value),filters:{jurisdictions:code?[scope]:[],courts:scope&&!code?[aliases[scope]||scope]:[],source_types:['statute','judgment']},options:{depth:'deep',connect_to_case_facts:true,include_secondary_sources:false}}});await followResearch(ticket);await loadResearchScreen();}finally{researchBusy=false;$('research-run').disabled=false;}});
$('research-files').onchange=safe(async()=>{if(researchBusy)throw new Error('Wait for the active task.');researchBusy=true;try{for(const file of $('research-files').files){$('research-progress').textContent='Uploading '+file.name;const ticket=await uploadFile(file,{document_type:$('research-upload-type').value,jurisdiction:$('research-upload-jurisdiction').value});const job=await waitResearch(ticket.job_id);if(job.failure)throw new Error(job.failure.message);}await loadResearchScreen();}finally{researchBusy=false;$('research-files').value='';}});
async function showResearch(id){const memo=await api('/api/v1/research/'+id),out=$('research-output');out.replaceChildren(node('h2','','Legal Research Memo'),node('p','',memo.question),node('p','model-status',memo.status+' · '+memo.model.version));if(memo.failure)out.append(node('p','notice',memo.failure.message));if(!terminal.has(memo.status)){const b=node('button','button primary','Follow this task');b.onclick=safe(async()=>{if(researchBusy)return;researchBusy=true;try{await followResearch({research_id:id,job_id:memo.job_id});}finally{researchBusy=false;}});out.append(b);return;}if(!memo.executive_summary)return;out.append(node('p','',memo.executive_summary.text));addCitations(out,memo,memo.executive_summary.citation_ids);for(const section of memo.legal_framework){out.append(node('h3','',section.heading),node('p','',section.analysis));addCitations(out,memo,section.citation_ids);}for(const item of memo.application_to_facts){out.append(node('h3','','Application to facts'),node('p','',item.analysis));addCitations(out,memo,[...item.fact_citation_ids,...item.law_citation_ids]);}for(const limitation of memo.limitations)out.append(node('p','notice',limitation));for(const sub of memo.sub_queries)out.append(node('p','muted-text',sub.question+' · '+sub.status));if(['completed','completed_with_warnings'].includes(memo.status))for(const format of ['json','docx','pdf']){const b=node('button','button subtle','Export '+format.toUpperCase());b.onclick=safe(async()=>{const blob=await api(`/api/v1/research/${id}/export?format=${format}`,{blob:true}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='legal-research.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);});out.append(b);}}
