import assert from 'node:assert/strict';
globalThis.window = {};
globalThis.location = {origin:'https://test.example'};
globalThis.sessionStorage = {getItem:()=>null,setItem:()=>{}};
globalThis.document = {createElement:()=>({setAttribute(){},classList:{add(){},remove(){}},append(){},addEventListener(){},querySelector(){return {addEventListener(){}};}}),body:{append(){},appendChild(){}},addEventListener(){}};
globalThis.localStorage = {getItem:()=>null,setItem:()=>{throw new Error('Storage unavailable');}};
const {DraftingView} = await import('../js/views/drafting.js');
const {ChatView} = await import('../js/views/chat.js');
const {LegalApiClient} = await import('../js/api/api-client.js');
const {ChatApi} = await import('../js/api/chat-api.js');
const listeners = {};
const field = {getAttribute:()=>'name',addEventListener:(event,fn)=>listeners[event]=fn};
const button = {disabled:true,addEventListener:()=>{}};
const status = {innerHTML:''};
const el = {innerHTML:'',querySelectorAll:()=>[field],querySelector:selector=>{
  if(selector==='.df-missing')return status;
  if(selector==='#df-generate')return button;
  throw new Error('Unexpected selector '+selector);
}};
const drafting = new DraftingView(el);
assert.doesNotThrow(()=>drafting._saveDraft());
drafting.requirements = [{id:'name',required:true,current_answer:null,question:'Name'}];
drafting._renderRequirements();
listeners.input({target:{getAttribute:()=>'name',value:'Example'}});
assert.equal(button.disabled,false);
assert.match(status.innerHTML,/All required fields answered/);
listeners.input({target:{getAttribute:()=>'name',value:' '}});
assert.equal(button.disabled,true);
assert.match(status.innerHTML,/1 required field/);
LegalApiClient.listDocuments = async()=>({data:[]});
let attempts = 0;
ChatApi.config = async()=>{if(++attempts===1)throw new Error('Temporary connection error');return {data:{model:'test'}};};
ChatApi.createConversation = async()=>({data:{conversation_id:'test'}});
const chat = new ChatView({});
chat._renderChat = async()=>{};
await assert.rejects(chat.render(),/Temporary connection error/);
assert.equal(chat.loaded,false);
await chat.render();
assert.equal(attempts,2);
assert.equal(chat.convoId,'test');
console.log('Drafting input updates, storage failure and chat initialization recovery passed.');

